package platform.notification;

public class NotificationFactory {
	public static byte SEVERIRY_CRITICAL  = 1;
	public static byte SEVERIRY_MAJOR  = 2;
	public static byte SEVERIRY_WARNING  = 3;
	public static byte SEVERIRY_MINOR  = 4;
	public static byte SEVERIRY_INFO  = 5;
	
	public static String NOTIFICATION_EXTERNAL_POWER_ON = "EXTERNAL_POWER_ON";
	public static String NOTIFICATION_EXTERNAL_POWER_OFF = "EXTERNAL_POWER_OFF";
	public static String NOTIFICATION_IGNITION_ON = "IGNITION_ON"; 
	public static String NOTIFICATION_IGNITION_OFF = "IGNITION_OFF";
	public static String NOTIFICATION_STARTED = "STARTED"; 
	public static String NOTIFICATION_STOPPED = "STOPPED";
	public static String NOTIFICATION_FUEL_ADDED = "FUEL_ADDED";
	public static String NOTIFICATION_STOP_REACHED = "STOP REACHED";
	public static String NOTIFICATION_OVER_SPEED = "OVER SPEED";
	public static String NOTIFICATION_HOMEWORK = "HOMEWORK";
	public static String NOTIFICATION_DAILY_ACTIVITY = "DAILY_ACTIVITY";
	public static String NOTIFICATION_INVITE_TO_JOIN_PARENT_CONNECT = "INVITE TO JOINT PARENT CONNECT";
	
	public static String NOTIFICATION_DATA_PARAMETER_LATITUDE = "LATITUDE";
	public static String NOTIFICATION_DATA_PARAMETER_LOGITUDE= "LOGITUDE";
	public static String NOTIFICATION_DATA_PARAMETER_SPEED= "SPEED";
	public static String NOTIFICATION_DATA_PARAMETER_ROUTE_NAME= "ROUTE_NAME";
	public static String NOTIFICATION_DATA_PARAMETER_VEHICLE_NAME= "VEHICLE_NAME";
	public static String NOTIFICATION_DATA_PARAMETER_ROUTE_ID= "ROUTE_ID";
	public static String NOTIFICATION_DATA_PARAMETER_ROUTE_STOPAGE_ID= "ROUTE_STOPAGE_ID";
	public static String NOTIFICATION_DATA_PARAMETER_STOPAGE_NAME= "STOPAGE_NAME";
	public static String NOTIFICATION_DATA_PARAMETER_SCHOOL_NAME= "SCHOOL_NAME";	
	public static String NOTIFICATION_DATA_PARAMETER_REACHED_DURATION= "REACHED_DURATION";
	public static String NOTIFICATION_DATA_PARAMETER_REACHED_TIME= "REACHED_TIME";
	public static String NOTIFICATION_DATA_PARAMETER_SCHOOL_ID= "SCHOOL_ID";
	public static String NOTIFICATION_DATA_PARAMETER_ACTIVITY_DATE= "ACTIVITY_DATE";
	public static String NOTIFICATION_DATA_PARAMETER_HOMEWORK_ID= "HOMEWORK_ID";
	public static String NOTIFICATION_DATA_PARAMETER_TEACHER_ID= "TEACHER_ID";
	public static String NOTIFICATION_DATA_PARAMETER_SUBJECT_ID= "SUBJECT_ID";
	public static String NOTIFICATION_DATA_PARAMETER_CLASS_SECTION_NAME= "CLASS_SECTION_NAME";
	public static String NOTIFICATION_DATA_PARAMETER_TITLE= "TITLE";
	public static String NOTIFICATION_DATA_PARAMETER_DESCRIPTION= "DESCRIPTION";
	public static String NOTIFICATION_DATA_PARAMETER_SUBMIT_DATE= "SUBMIT_DATE";
	public static String NOTIFICATION_DATA_PARAMETER_DAILY_ACTVITY_ID= "DAILY_ACTVITY_ID";
	
	
	
}
