/*
 * Copyright 2010-2020 M16, Inc. All rights reserved.
 * This software and documentation contain valuable trade
 * secrets and proprietary property belonging to M16, Inc.
 * None of this software and documentation may be copied,
 * duplicated or disclosed without the express
 * written permission of M16, Inc.
 */

package application.c4t.vehicle.school.defined;

import platform.defined.ResourceMap;


public class ResourcesToGenerate {
	/*
	 * Define each element in the format of {"<json_file_name>", "<fully_qualified_resource_path_name>","<db_name>"}
	 * json_file_name - specify only the file name without extension
	 * fully_qualified_resource_path_name - not that of generated class but that of extending class. If there is no extending class, leave it null (Ex: Sample)
	 * db_name - instance of DBNameEnum where this resource will stored. null if resource is transient (not stored in DB)
	 * Make sure there is a default constructor (with no args) in the extending class.
	 */
	public static ResourceMap[] resourceMaps =  {
		new ResourceMap("student", "application.c4t.vehicle.school.resource.student"),
		new ResourceMap("school_route_map", "application.c4t.vehicle.school.resource.school_route_map"),
		new ResourceMap("school_route_stopage_map", "application.c4t.vehicle.school.resource.school_route__stopage_map"),
		new ResourceMap("student_map", "application.c4t.vehicle.school.resource.student_map"),
		new ResourceMap("school_user_map", "application.c4t.vehicle.school.resource.school_user_map"),
		new ResourceMap("school_customer_map", "application.c4t.vehicle.school.resource.school_customer_map"),
		new ResourceMap("student_parent", "application.c4t.vehicle.school.resource.student_parent"),
		new ResourceMap("student_detail", "application.c4t.vehicle.school.resource .student_detail"),
		new ResourceMap("school", "application.c4t.vehicle.school.resource.school"),
		new ResourceMap("school_group", "application.c4t.vehicle.school.resource.school_group"),
		new ResourceMap("school_customer", "application.c4t.vehicle.school.resource.school_customer"),
		new ResourceMap("school_customer_admin", "application.c4t.vehicle.school.resource.school_customer_admin"),
		new ResourceMap("school_map", "application.c4t.vehicle.school.resource.school_map"),
		new ResourceMap("teacher", "application.c4t.vehicle.school.resource.teacher"),
		new ResourceMap("teacher_map", "application.c4t.vehicle.school.resource.teacher_map"),
		new ResourceMap("class_section", "application.c4t.vehicle.school.resource.class_section"),
		new ResourceMap("subject", "application.c4t.vehicle.school.resource.subject"),
		new ResourceMap("teacher_subject", "application.c4t.vehicle.school.resource.teacher_subject"),
		new ResourceMap("homework", "application.c4t.vehicle.school.resource.homework"),
		new ResourceMap("home_practice", "application.c4t.vehicle.school.resource.home_practice"),
		new ResourceMap("homework_master", "application.c4t.vehicle.school.resource.homework_master"),
		new ResourceMap("daily_activity", "application.c4t.vehicle.school.resource.daily_activity"),
		new ResourceMap("daily_activity_calender", "application.c4t.vehicle.school.resource.daily_activity_calender"),
		new ResourceMap("notice", "application.c4t.vehicle.school.resource.notice"),
		new ResourceMap("absent", "application.c4t.vehicle.school.resource.absent"),
		new ResourceMap("absent_detail", "application.c4t.vehicle.school.resource.absent_detail"),
		new ResourceMap("message2parent", "application.c4t.vehicle.school.resource.message2parent"),
		new ResourceMap("message2parent_conversation", "application.c4t.vehicle.school.resource.message2parent_conversation"),
		new ResourceMap("message2school", "application.c4t.vehicle.school.resource.message2parent"),
		new ResourceMap("message2school_conversation", "application.c4t.vehicle.school.resource.message2parent_conversation"),
		new ResourceMap("grievance", "application.c4t.vehicle.school.resource.grievance"),
		new ResourceMap("grievance_conversation", "application.c4t.vehicle.school.resource.grievance"),
		new ResourceMap("proficiency_master", "application.c4t.vehicle.school.resource.proficiency_master"),
		new ResourceMap("proficiency", "application.c4t.vehicle.school.resource.proficiency"),
		new ResourceMap("report_card", "application.c4t.vehicle.school.resource.report_card"),
		new ResourceMap("report_card_generation_request", "application.c4t.vehicle.school.resource.report_card_geneartion_request"),
		new ResourceMap("school_class_section", "application.c4t.vehicle.school.resource.school_class_section"),
		new ResourceMap("topic", "application.c4t.vehicle.school.resource.topic"),
		new ResourceMap("chapter", "application.c4t.vehicle.school.resource.chapter"),
		new ResourceMap("work_sheet", "application.c4t.vehicle.school.resource.work_sheet"),
		new ResourceMap("work_sheet_result", "application.c4t.vehicle.school.resource.work_sheet_result"),
		new ResourceMap("assessment_period", "application.c4t.vehicle.school.resource.assessment_period"),
		new ResourceMap("signature", "application.c4t.vehicle.school.resource.signature"),
		new ResourceMap("school_event", "application.c4t.vehicle.school.resource.school_event"),
		new ResourceMap("present", "application.c4t.vehicle.school.resource.present"),
		new ResourceMap("present_detail", "application.c4t.vehicle.school.resource.present_detail"),
		new ResourceMap("news", "application.c4t.vehicle.school.resource.news"),		
		new ResourceMap("parenting", "application.c4t.vehicle.school.resource.parenting"),		
		new ResourceMap("medical_record", "application.c4t.vehicle.school.resource.medical_record"),		
		new ResourceMap("medical_record_date_wise", "application.c4t.vehicle.school.resource.medical_record_date_wise"),		
		new ResourceMap("school_timing", "application.c4t.vehicle.school.resource.school_timing"),		
		new ResourceMap("trip_student_detail", "application.c4t.vehicle.school.resource.trip_student_detail"),		
		new ResourceMap("staff", "application.c4t.vehicle.school.resource.staff"),		
		new ResourceMap("designation", "application.c4t.vehicle.school.resource.designation"),		
		new ResourceMap("department", "application.c4t.vehicle.school.resource.department"),		
		new ResourceMap("staff_present", "application.c4t.vehicle.school.resource.staff_present"),		
		new ResourceMap("staff_present_detail", "application.c4t.vehicle.school.resource.staff_present_detail"),		
		new ResourceMap("staff_timing", "application.c4t.vehicle.school.resource.staff_timing"),		
		new ResourceMap("direct_message", "application.c4t.vehicle.school.resource.direct_message"),		
		new ResourceMap("tutorial", "application.c4t.vehicle.school.resource.tutorial"),		
		new ResourceMap("tutorial_category", "application.c4t.vehicle.school.resource.tutorial_category"),		
		new ResourceMap("objective_question", "application.c4t.vehicle.school.resource.objective_question"),		
		new ResourceMap("practical_master", "application.c4t.vehicle.school.resource.practical_master"),		
		new ResourceMap("doubt", "application.c4t.vehicle.school.resource.doubt"),		
		new ResourceMap("doubt_conversation", "application.c4t.vehicle.school.resource.doubt_conversation"),		
		new ResourceMap("student_tutorial", "application.c4t.vehicle.school.resource.student_tutorial"),		
		new ResourceMap("student_tutorial_history", "application.c4t.vehicle.school.resource.student_tutorial_history"),		
		new ResourceMap("practical_attendance", "application.c4t.vehicle.school.resource.practical_attendance"),		
		new ResourceMap("photo", "application.c4t.vehicle.school.resource.photo"),	
		new ResourceMap("photo_collection", "application.c4t.vehicle.school.resource.photo_collection"),	
		new ResourceMap("video", "application.c4t.vehicle.school.resource.video"),	
		new ResourceMap("video_collection", "application.c4t.vehicle.school.resource.video_collection"),	
		new ResourceMap("course", "application.c4t.vehicle.school.resource.course"),	
		new ResourceMap("fee_master", "application.c4t.vehicle.school.resource.fee_master"),	
		new ResourceMap("fee_heading", "application.c4t.vehicle.school.resource.fee_heading"),	
		new ResourceMap("fee_schedule", "application.c4t.vehicle.school.resource.fee_schedule"),	
		new ResourceMap("fee_breakup", "application.c4t.vehicle.school.resource.fee_breakup"),	
		new ResourceMap("fee_additional_charge", "application.c4t.vehicle.school.resource.fee_additional_charge"),	
		new ResourceMap("timetable", "application.c4t.vehicle.school.resource.timetable"),	
		new ResourceMap("timetable_interface", "application.c4t.vehicle.school.resource.timetable_interface"),	
		new ResourceMap("fee_receipt", "application.c4t.vehicle.school.resource.fee_receipt"),	
		new ResourceMap("fee_discount", "application.c4t.vehicle.school.resource.fee_discount"),	
		new ResourceMap("holiday", "application.c4t.vehicle.school.resource.holiday"),	
		new ResourceMap("account_heading", "application.c4t.vehicle.school.resource.account_heading"),	
		new ResourceMap("school_account", "application.c4t.vehicle.school.resource.school_account"),	
		new ResourceMap("account_year", "application.c4t.vehicle.school.resource.account_year"),	
		new ResourceMap("account_transaction", "application.c4t.vehicle.school.resource.account_transaction"),	
		new ResourceMap("student_photo", "application.c4t.vehicle.school.resource.student_photo"),	
		new ResourceMap("test", "application.c4t.vehicle.school.resource.test"),	
		new ResourceMap("test_question", "application.c4t.vehicle.school.resource.test_question"),	
		new ResourceMap("batch", "application.c4t.vehicle.school.resource.batch"),
		new ResourceMap("batch_signup_test", "application.c4t.vehicle.school.resource.batch_signup_test"),
		new ResourceMap("batch_signup_book", "application.c4t.vehicle.school.resource.batch_signup_book"),
		new ResourceMap("objective_question_answers", "application.c4t.vehicle.school.resource.objective_question_answers"),
		new ResourceMap("objective_question_answer", "application.c4t.vehicle.school.resource.objective_question_answer"),
		new ResourceMap("test_allocation", "application.c4t.vehicle.school.resource.test_allocation"),
		new ResourceMap("test_allocation_student", "application.c4t.vehicle.school.resource.test_allocation_student"),
		new ResourceMap("book", "application.c4t.vehicle.school.resource.book"),
		new ResourceMap("book_chapter", "application.c4t.vehicle.school.resource.book_chapter"),
		new ResourceMap("test_group", "application.c4t.vehicle.school.resource.test_group"),		
		new ResourceMap("book_chapter_test", "application.c4t.vehicle.school.resource.book_chapter_test"),
		new ResourceMap("book_chapter_section", "application.c4t.vehicle.school.resource.book_chapter_section"),		
		new ResourceMap("book_allocation", "application.c4t.vehicle.school.resource.book_allocation"),
		new ResourceMap("book_allocation_student", "application.c4t.vehicle.school.resource.book_allocation_student"),
		new ResourceMap("homepage_current_affair", "application.c4t.vehicle.school.resource.homepage_current_affair"),
		new ResourceMap("homepage_article", "application.c4t.vehicle.school.resource.homepage_article"),
		new ResourceMap("homepage_link", "application.c4t.vehicle.school.resource.homepage_link"),
		new ResourceMap("homepage_video", "application.c4t.vehicle.school.resource.homepage_video"),
		new ResourceMap("recharge", "application.c4t.vehicle.school.resource.recharge"),
		new ResourceMap("homepage_rank_holder", "application.c4t.vehicle.school.resource.homepage_rank_holder")
	};
}
